Should be within `f` now:
InterpretSnapshot:
  isStatus: running / faced statement
  isStackFrames:
    [StackFrame:
      sfName: f
      sfLoc: test/contracts/functions-visiting.mligo@2:5-2:20
      sfStack:
        [StackItem:
          siLigoDesc: elem a of int
          siValue: 1
        ]
    , StackFrame:
      sfName: main
      sfLoc: test/contracts/functions-visiting.mligo@12:18-12:23
      sfStack:
        [StackItem:
          siLigoDesc: elem s2 of int
          siValue: 1
        , StackItem:
          siLigoDesc: elem g of unit -> int
          siValue: { DROP; { { { PUSH int 10 }; { PUSH int 10 }; ADD }; {  }; {  } } }
        , StackItem:
          siLigoDesc: elem f of int -> int
          siValue: { {  }; { { { PUSH int 100 }; { SWAP }; ADD }; {  }; { { { PUSH int 100 }; { SWAP }; ADD }; {  }; {  } } } }
        ]
    ]

Stepping out, now should appear outside of the method despite the breakpoint
InterpretSnapshot:
  isStatus: running / expression evaluated (201)
  isStackFrames:
    [StackFrame:
      sfName: main
      sfLoc: test/contracts/functions-visiting.mligo@12:18-12:23
      sfStack:
        [StackItem:
          siLigoDesc: elem s2 of int
          siValue: 1
        , StackItem:
          siLigoDesc: elem g of unit -> int
          siValue: { DROP; { { { PUSH int 10 }; { PUSH int 10 }; ADD }; {  }; {  } } }
        , StackItem:
          siLigoDesc: elem f of int -> int
          siValue: { {  }; { { { PUSH int 100 }; { SWAP }; ADD }; {  }; { { { PUSH int 100 }; { SWAP }; ADD }; {  }; {  } } } }
        ]
    ]
